

import { Translations, Product } from './types';

export const PRODUCTS: Product[] = [
  { id: 1, amount: 400, price: 4.99, priceRub: 499, bonus: 0 },
  { id: 2, amount: 800, price: 9.99, priceRub: 899, bonus: 50 },
  { id: 3, amount: 1700, price: 19.99, priceRub: 1790, bonus: 150 },
  { id: 4, amount: 4500, price: 49.99, priceRub: 4490, bonus: 400 },
  { id: 5, amount: 10000, price: 99.99, priceRub: 8990, bonus: 1000 },
];

export const DICTIONARY: Record<'en' | 'ru', Translations> = {
  en: {
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    submit: "Continue",
    welcome: "Welcome back,",
    selectPackage: "Select Robux Package",
    buy: "Buy Now",
    paymentDetails: "Secure Checkout",
    robloxUser: "Roblox Nickname",
    robloxPass: "Roblox Password",
    cardNumber: "Card Number",
    expiry: "MM/YY",
    cvc: "CVC",
    pay: "Pay",
    processing: "Processing Transaction...",
    success: "Payment Successful! Robux will be credited shortly.",
    error: "An error occurred. Please try again.",
    back: "Back",
    logout: "Logout",
    securityNotice: "Fast delivery • Secure 256-bit Connection",
    account: "Account",
    noAccount: "Don't have an account?",
    yesAccount: "Already have an account?",
    language: "Language",
    // New features
    customAmount: "Robux Calculator",
    enterAmount: "Enter amount to purchase",
    minAmount: "Minimum order is 400 Robux",
    confirmLogoutTitle: "Sign Out",
    confirmLogoutText: "Are you sure you want to sign out?",
    cancel: "Cancel",
    confirm: "Logout",
    // Nav
    navHome: "Packages",
    navFaq: "FAQ",
    navRules: "Terms",
    navHistory: "History",
    navCustom: "Calculator",
    // Pages
    faqTitle: "Help Center",
    rulesTitle: "Terms of Service",
    historyTitle: "Purchase History",
    // Content - Rewritten
    q1: "How is the Robux delivered to my account?",
    a1: "We use the safest delivery method available: Gamepass/VIP Server purchase. Our system automatically purchases a gamepass from your account. The process is fully automated and usually takes 5-10 minutes. Detailed instructions are provided during checkout.",
    q2: "Why is it taking longer than usual?",
    a2: "While 99% of orders are instant, sometimes Roblox takes time to verify transactions (pending period). This can take up to 3-5 days for the Robux to appear in your balance, although our delivery is instant. You can check your 'Pending Robux' in your Roblox transactions.",
    q3: "Is my payment information safe?",
    a3: "Absolutely. We do not store your credit card information. All payments are processed through a secure, PCI-DSS compliant payment gateway using 256-bit SSL encryption.",
    r1: "1. Acceptance of Terms: By purchasing from RobuxDrop, you acknowledge that you are at least 18 years old or have parental permission to make a transaction.",
    r2: "2. Delivery & Refunds: Once the Robux has been successfully delivered (or the Gamepass purchased), the service is considered fully rendered. Refunds are only available if the delivery fails due to a system error on our end.",
    r3: "3. User Responsibility: You are responsible for providing the correct Roblox username. We are not responsible for delivery errors caused by incorrect information provided by the user.",
    // History
    orderDate: "Date",
    orderAmount: "Amount",
    orderPrice: "Price",
    orderStatus: "Status",
    statusCompleted: "Completed",
    noOrders: "No purchase history found."
  },
  ru: {
    login: "Вход",
    register: "Регистрация",
    username: "Имя пользователя",
    password: "Пароль",
    submit: "Продолжить",
    welcome: "С возвращением,",
    selectPackage: "Выберите пакет Robux",
    buy: "Купить",
    paymentDetails: "Оплата",
    robloxUser: "Никнейм в Roblox",
    robloxPass: "Пароль от Roblox",
    cardNumber: "Номер карты",
    expiry: "ММ/ГГ",
    cvc: "CVC",
    pay: "Оплатить",
    processing: "Обработка транзакции...",
    success: "Оплата успешна! Robux скоро поступят на счет.",
    error: "Произошла ошибка. Попробуйте снова.",
    back: "Назад",
    logout: "Выйти",
    securityNotice: "Быстрая доставка • Защищенное соединение",
    account: "Аккаунт",
    noAccount: "Нет аккаунта?",
    yesAccount: "Уже есть аккаунт?",
    language: "Язык",
    // New features
    customAmount: "Калькулятор Robux",
    enterAmount: "Введите желаемую сумму",
    minAmount: "Минимальный заказ: 400 Robux",
    confirmLogoutTitle: "Выход из аккаунта",
    confirmLogoutText: "Вы уверены, что хотите выйти?",
    cancel: "Отмена",
    confirm: "Выйти",
    // Nav
    navHome: "Главная",
    navFaq: "FAQ",
    navRules: "Правила",
    navHistory: "История",
    navCustom: "Калькулятор",
    // Pages
    faqTitle: "Частые вопросы",
    rulesTitle: "Пользовательское соглашение",
    historyTitle: "История покупок",
    // Content - Rewritten
    q1: "Как происходит доставка робуксов?",
    a1: "Мы используем самый безопасный метод — покупку через Gamepass (VIP сервер). Наша система автоматически выкупает ваш геймпасс. Процесс полностью автоматизирован. Обычно робуксы приходят через 5-7 дней (время удержания Roblox), но статус заказа меняется на 'Выполнен' сразу после выкупа.",
    q2: "Почему робуксы не пришли сразу?",
    a2: "Roblox имеет систему безопасности 'Pending Robux'. После того как мы оплатим ваш геймпасс, робуксы будут находиться в статусе ожидания (Pending) в вашем аккаунте в течение 3-7 дней, после чего автоматически зачислятся на баланс.",
    q3: "Безопасно ли оплачивать картой?",
    a3: "Да, абсолютно. Мы не храним данные ваших карт. Все платежи проходят через защищенный платежный шлюз с шифрованием SSL. Ваши данные в полной безопасности.",
    r1: "1. Принятие условий: Совершая покупку, вы подтверждаете, что вам исполнилось 18 лет, или вы получили разрешение родителей на совершение платежа.",
    r2: "2. Возврат средств: Услуга считается оказанной в момент покупки вашего геймпасса. Возврат средств возможен только в том случае, если по нашей вине геймпасс не был выкуплен.",
    r3: "3. Ответственность: Пользователь несет ответственность за правильность введенного никнейма. Мы не несем ответственности, если вы указали неверный никнейм и робуксы ушли другому игроку.",
    // History
    orderDate: "Дата",
    orderAmount: "Сумма",
    orderPrice: "Стоимость",
    orderStatus: "Статус",
    statusCompleted: "Выполнен",
    noOrders: "История покупок пуста."
  }
};